FROM gradle:jdk17 as build

WORKDIR /src
COPY . /src
RUN ./gradlew build

FROM eclipse-temurin:17.0.4.1_1-jre

COPY --from=build /src/build/libs .
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "randomNumbers-1.0.jar"]