FROM gradle:jdk17 as build

WORKDIR /src
COPY . /src
RUN ./gradlew build

FROM eclipse-temurin:17.0.4.1_1-jre

COPY --from=build /src/build/libs .
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.17.0/opentelemetry-javaagent.jar .
EXPOSE 8081
ENTRYPOINT ["java", "-javaagent:opentelemetry-javaagent.jar", "-jar", "randomLetters-1.0.jar"]